services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Lochmueller\Index\Indexing\Database\Extender\ExtenderInterface:
      tags: [ 'index.extenders' ]
    Lochmueller\Index\Indexing\Database\Types\TypeInterface:
      tags: [ 'index.types' ]

  Lochmueller\Index\:
    resource: '../Classes/*'