services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Lochmueller\Index\:
    resource: '../Classes/*'

  Lochmueller\Index\FileExtraction\FileExtractor:
    public: true