services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Lochmueller\Index\Indexing\Database\Extender\ExtenderInterface:
      tags: [ 'index.extenders' ]

  Lochmueller\Index\:
    resource: '../Classes/*'

  Lochmueller\FileExtractor\FileExtractor:
    public: true